CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_boards_author_name UNIQUE (author_id, name),
    CONSTRAINT fk_boards_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE board_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_board_columns_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE,
    CONSTRAINT uk_board_columns_status UNIQUE (board_id, status),
    CONSTRAINT chk_board_columns_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_board_columns_position CHECK (position BETWEEN 0 AND 2)
);

CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(4000),
    status VARCHAR(30) NOT NULL,
    position INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cards_board FOREIGN KEY (board_id) REFERENCES boards (id) ON DELETE CASCADE,
    CONSTRAINT chk_cards_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_cards_position CHECK (position >= 0)
);

CREATE INDEX idx_boards_author_id ON boards (author_id);
CREATE INDEX idx_board_columns_board_position ON board_columns (board_id, position);
CREATE INDEX idx_cards_board_status_position ON cards (board_id, status, position);
